import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "react-toastify/dist/ReactToastify.css";
import Providers from "./providers";
import { Inter } from "next/font/google";
export const metadata = {
  title: "HUMAN RELIEF CHARITABLE TEAM",
  description: "Generated by HUMAN RELIEF CHARITABLE TRUE SANSTHAN",
};
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers>

      </body>
    </html>
  );
}
