import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "react-toastify/dist/ReactToastify.css";
import Providers from "./providers";
export const metadata = {
  title: "HUMAN RELIEF CHARITABLE TEAM",
  description: "Generated by HUMAN RELIEF CHARITABLE TRUE SANSTHAN",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>

      </body>
    </html>
  );
}
